テキスト教材・動画教材ページの追加
yanbaru-expert/team_project_50 pull request #27
Opened 2021-05-05 13:27 UTC by watanabe420

close #2 

## 実装内容
- `texts`コントローラーと`movies`コントローラーを作成
  - 作成されたビューファイルの中身は空にする

- ルーティングをresourcesで以下のように設定
  - onlyを使用して、使用するアクションを制限
  - textsコントローラーのindexアクションに対応するビューをトップページに設定

```
Rails.application.routes.draw do
  root "texts#index"
  resources :texts, :only => [:index, :show]
  resources :movies, :only => [:index]
end
```

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-05-05 13:40 UTC, T-Tsujii requested changes

2021-05-05 13:40 UTC, T-Tsujii commented on config/routes.rb
> +  resources :movies, :only => [:index]
今はこちらの書き方が普通ですね。（RuboCopなら指摘されます）

```suggestion
  resources :texts, only: [:index, :show]
  resources :movies, only: [:index]
```

2021-05-06 02:18 UTC, watanabe420 commented on config/routes.rb
> +  resources :movies, :only => [:index]
承知しました！
修正いたします。

2021-05-06 02:54 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-06 04:22 UTC, C-Issei approved these changes
LGTMです！

2021-05-06 04:33 UTC, yasu-grz commented
LGTMです！

2021-05-06 04:36 UTC, yasu-grz commented
LGTMです！

2021-05-06 04:52 UTC, yasu-grz approved these changes
LGTMです！

2021-05-06 11:41 UTC, akihiro-cmd commented
LGTMです！

2021-05-06 12:06 UTC, merged