#4モデル・テーブルの作成
yanbaru-expert/team_project_50 pull request #28
Opened 2021-05-05 13:57 UTC by yasu-grz

close #4

## 実装内容
次のモデル・テーブルを作成
- Textモデルとtextsテーブルを作成
  - カラムは「`genre`（`integer型`）」「`title`（`string型`）」「`content`（`text型`）」
  - 全て`NOT NULL`制約を入れる
  - `genre`カラムのデフォルト値は`0`とする
- Movieモデルとmoviesテーブルを作成
  - カラムは「`genre`（`integer型`）」「`title`（`string型`）」「`url`（`string型`）」
  - 全て`NOT NULL`制約を入れる
  - `genre`カラムのデフォルト値は`0`とする
`NOT NULL`制約と`genre`カラムのデフォルト値を設定してから、マイグレーションを実行する。
※モデルのバリデーションは別タスクとする
## 動作確認
ターミナルから以下を実行し、「`NOT NULL`制約が入っていること」と「`genre`カラムのデフォルト値が`0`になっていること」を確認。
```shell
rails db

# PostgreSQL に接続後
\d texts
\d movies

# 確認後
exit
```

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-05-05 14:38 UTC, T-Tsujii requested changes
マイグレーションを実行し忘れていませんか？

2021-05-05 14:49 UTC, yasu-grz commented
おつかれさまです。ログを見てプルリク前にマイグレーションは実行済していると思います。
念の為、再度マイグレーションを行いましたが下記のエラー分が表示されました。
~/rails/team_project_50 feature/model_table 5m 49s
❯ rails db:migrate
== 20210505051404 CreateTexts: migrating ======================================
-- create_table(:texts)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "texts" already exists
/Users/uehy/rails/team_project_50/db/migrate/20210505051404_create_texts.rb:3:in `change'
/Users/uehy/rails/team_project_50/bin/rails:5:in `<top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:10:in `block in <top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:7:in `tap'
/Users/uehy/rails/team_project_50/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "texts" already exists
/Users/uehy/rails/team_project_50/db/migrate/20210505051404_create_texts.rb:3:in `change'
/Users/uehy/rails/team_project_50/bin/rails:5:in `<top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:10:in `block in <top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:7:in `tap'
/Users/uehy/rails/team_project_50/bin/spring:7:in `<top (required)>'

Caused by:
PG::DuplicateTable: ERROR:  relation "texts" already exists
/Users/uehy/rails/team_project_50/db/migrate/20210505051404_create_texts.rb:3:in `change'
/Users/uehy/rails/team_project_50/bin/rails:5:in `<top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:10:in `block in <top (required)>'
/Users/uehy/rails/team_project_50/bin/spring:7:in `tap'
/Users/uehy/rails/team_project_50/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

2021-05-06 00:08 UTC, yasu-grz commented
修正致しましたので、確認のほどよろしくお願いします。

2021-05-06 04:20 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-06 04:29 UTC, C-Issei approved these changes
LGTMです！

2021-05-06 05:59 UTC, merged

2021-05-06 11:39 UTC, akihiro-cmd commented
LGTMです！