Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_50 pull request #41
Opened 2021-05-27 06:48 UTC by yasu-grz

close #13

## 実装内容
#8 #9 #10 完了後に行ってください
- `app/models/text.rb` に次を定義
```  rb
RAILS_GENRE_LIST = %w[basic git ruby rails]
```
- Railsテキスト教材の一覧ページを作成
  * 表示するジャンルは `Text::RAILS_GENRE_LIST` に制限
  * Bootstrapの `Cards` や `Grid System` を用いて下図のようなスタイルにすること
  * `each`を使わず「[コレクションをレンダリング](https://railsguides.jp/layouts_and_rendering.html)」を利用しましょう
  * 画像部分は [デフォルト画像](https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg) を表示するのみとする
  * カードの `height`, `max-width` を指定すること
  * テキスト教材ページでしか利用しないスタイルは `app/assets/stylesheets/texts.scss` を作成して書き込むこと
  * 検索機能は実装しない
  * 広告は実装しない
  * カード全体を「詳細ページ」へのリンクにする作業は別タスクとする
  * 「読破済みボタン」はボタンの配置のみとする。（機能は別タスクで実装）
  
![image](https://user-images.githubusercontent.com/80580429/116790213-166b4800-aaee-11eb-980e-0fb54dff6cec.png)
![image](https://user-images.githubusercontent.com/80580429/116790314-6cd88680-aaee-11eb-9394-8b64f418b50e.png)
![image](https://user-images.githubusercontent.com/80580429/116790326-782bb200-aaee-11eb-8623-bab4434a6f4e.png)
## 参考文献
- [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
- [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)
## 動作確認
- 画像のようにレスポンシブ対応ができているかどうかを確認
- ブラウザの横幅次第でカードの横幅が長くなりすぎていないか確認
- PHPのテキスト教材が表示されていないことを確認

原則，マークダウン記法のリストで記載すること

(例)

- リスト1
  - リスト1-1
  - リスト1-2  

## 参考資料（必要があれば）

マークダウン記法のリンクを用いて記載すること

(例)

- ログイン機能
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/219)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-05-28 08:19 UTC, T-Tsujii requested changes

2021-05-28 08:19 UTC, T-Tsujii commented on app/assets/stylesheets/texts.scss
> +.card {
`.card` は Bootstrap で使用されているクラスですので，ここにCSSを当てると他で `.card` を使用した際に想定外のスタイルが付いてしまいます。

原則として他のクラス名を追加して対応しましょう。
複数人での開発では特に重要な考え方です。

2021-05-28 08:19 UTC, T-Tsujii commented on app/assets/stylesheets/texts.scss
> +}
こちらはimgタグ全体に定義されているのでさらに影響が大きいですね。
他のクラス名を入れて対応すべきです。

2021-05-28 08:19 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: ["basic", "git", "ruby", "rails"])
定数を利用した形式にしましょう。

```suggestion
    @texts = Text.where(genre: Text::RAILS_GENRE_LIST)
```

2021-05-28 08:19 UTC, T-Tsujii commented on app/models/text.rb
> +  RAILS_GENRE_LIST = %w[basic git ruby rails]
配列の定数は `freeze` で変更できないようにしておきましょう。

```suggestion
  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze
```

2021-05-29 09:47 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-29 13:09 UTC, C-Issei commented
LGTMです！

2021-05-29 13:11 UTC, C-Issei approved these changes
LGTMです！お疲れ様でした。

2021-05-29 13:53 UTC, merged