動画教材ページのジャンル分け
yanbaru-expert/team_project_50 pull request #45
Opened 2021-06-06 06:23 UTC by C-Issei

close #18 

## 実装内容

- PHP動画教材ページで「PHP動画教材のみ」が表示されるように修正
  - クエリパラメータ`?genre=php`を利用
- 「Ruby/Rails動画教材ページ」のタイトルは「Ruby/Rails 動画」，「PHP動画教材ページ」のタイトルは「PHP動画」とした
  - `app/helpers/application_helper.rb`にメソッドを作成して対応

## 参考資料

- [クエリパラメータについて](https://mseeeen.msen.jp/ruby-on-rails2/)
- [ヘルパーの使い方](https://qiita.com/sanstktkrsyhsk/items/67e9d88b939ccdcf46e8)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-06-08 13:14 UTC, T-Tsujii requested changes

2021-06-08 13:14 UTC, T-Tsujii commented on app/models/movie.rb
> +  def self.filter_by(params)
genreを渡しているので，引数は `genre` の方がよいですね。

2021-06-08 13:26 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-09 01:56 UTC, yasu-grz approved these changes

2021-06-09 01:57 UTC, yasu-grz approved these changes
LGTMです！

2021-06-09 11:24 UTC, merged