PHPテキスト教材ページをジャンル分け
yanbaru-expert/team_project_50 pull request #47
Opened 2021-06-12 11:49 UTC by watanabe420

close #20  

## 実装内容

#13, #18 完了後に行って下さい

- PHPテキスト教材ページで「PHPのテキスト教材のみ」が表示されるように修正
  - `PHPテキスト教材` のリンクをクリックした際のクエリパラメータ `?genre=php` を利用
  - モデルにクラスメソッドを作成して対応

- 「Ruby/Railsテキスト教材ページ」のタイトルは「Ruby/Rails テキスト教材」，「PHPテキスト教材ページ」のタイトルは「PHP テキスト教材」とする
  - #18 の `app/helpers/application_helper.rb` にメソッドを作成して対応

## 動作確認

- 「Ruby/Railsテキスト教材」に「PHPテキスト教材」が含まれていないことを確認
- 「PHPテキスト教材」に「PHPテキスト教材」のみが表示されていることを確認
- クエリパラメータ `?genre=php` を `php` 以外に変更してアクセスした際は「Ruby/Railsテキスト教材」が表示されることを確認

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-06-12 13:16 UTC, T-Tsujii requested changes

2021-06-12 13:16 UTC, T-Tsujii commented on app/helpers/application_helper.rb
> +      "PHP テキスト教材"
動画教材でも利用したいので，メソッド名も含め工夫してみて下さい。

2021-06-12 13:16 UTC, T-Tsujii commented on app/models/text.rb
> +  PHP_GENRE_LIST = %w[php]
定数の配列には `freeze` を入れておきましょう。

```suggestion
  PHP_GENRE_LIST = %w[php].freeze
```

2021-06-17 03:49 UTC, T-Tsujii commented
コンフリクトの解消をお願いします！

2021-06-17 03:50 UTC, T-Tsujii commented on app/helpers/application_helper.rb
> +      "PHP テキスト教材"
「動画教材」「テキスト教材」はビューファイルに直接書けば良いので，重要なのはジャンルを条件分岐で表示することです。

2021-06-17 10:14 UTC, T-Tsujii requested changes

2021-06-17 10:14 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @texts = Text.filter_by(params[:genre])
`includes(:read_progresses)` を入れておかないと N + 1 問題が起きます。

2021-06-17 11:03 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-17 11:40 UTC, yasu-grz approved these changes
LGTMです！

2021-06-18 08:56 UTC, merged