動画教材の読破済み機能を実装
yanbaru-expert/team_project_50 pull request #49
Opened 2021-06-13 13:31 UTC by yasu-grz

close #23

## 実装内容

#15 完了後に行って下さい

- 視聴済み機能に使用する `WatchProgress` モデルを作成
  - 外部キー設定を行い，ユニーク制約を入れてからマイグレーション
  - バリデーションをモデルに追加
  - 関連付けを入れる（`User` と `Movie` の関連付けは使用しないので入れなくてもOK）
  - 初期データの実装は不要です

（この時点で下記の動作確認を行ってみましょう）

- 動画教材一覧ページに視聴済み機能を実装
  - 非同期で処理できるようにすること

## 参考文献

- [【やんばるエキスパート教材】モデルの関連付け その2（多対多）](https://www.yanbaru-code.com/texts/297)

## 動作確認

- 以下を確認

```zsh
rails c -s

# Railsコンソール起動後
user = User.first
movie, movie2 = Movie.limit(2)
WatchProgress.delete_all

user.watch_progresses.create!(movie_id: movie.id)
user.watch_progresses.create!(movie_id: movie2.id)

WatchProgress.count
#=> 2

movie.watch_progresses.create!(user_id: user.id)
#=> ActiveRecord::RecordInvalid: バリデーションに失敗しました: Userは同じ動画教材を2回以上視聴済みにはできません

WatchProgress.create!
#=> ActiveRecord::RecordInvalid: バリデーションに失敗しました: ユーザーを入力してください, 動画教材を入力してください
```

- 動画教材一覧ページの視聴済み機能が動作していることを確認

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-06-13 14:34 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-13 14:35 UTC, T-Tsujii commented
LGTMですが、コンフリクトの解消をお願いします！

2021-06-14 12:57 UTC, T-Tsujii requested changes

2021-06-14 12:57 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.includes(:watch_progresses).where(genre: Movie::RAILS_GENRE_LIST).filter_by(params[:genre]).page(params[:page]).per(PER_PAGE)
モデルに定義された `filter_by` メソッドの意味を考えて調整しましょう。

2021-06-15 10:56 UTC, T-Tsujii requested changes
読破済みボタンが動作していませんが，動作確認されましたか?

2021-06-15 10:56 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: Movie::RAILS_GENRE_LIST).page(params[:page]).per(PER_PAGE).includes(:watch_progresses)
これではPHP教材に対応できなくなります。

2021-06-15 12:34 UTC, yasu-grz commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: Movie::RAILS_GENRE_LIST).page(params[:page]).per(PER_PAGE).includes(:watch_progresses)
ご指摘ありがとうございます。
視聴済みの動作確認をして提出をさせて頂いたつもりではありますが、再度確認してみます。

2021-06-15 22:05 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-16 15:00 UTC, C-Issei approved these changes
LGTMです！

2021-06-16 21:51 UTC, merged