管理者画面から教材を編集できるように修正
yanbaru-expert/team_project_50 pull request #53
Opened 2021-06-22 13:41 UTC by C-Issei

close #52 

## 実装内容
- 管理者画面より教材を編集・修正できるようにする
  - `movies.rb`と`texts.rb`の以下のコメントアウトを表示
  ```Ruby
  permit_params do
    permitted = [:genre, :title, :url]
  end
  ```

## 参考資料
- [ストロングパラメータについて(ActiveAdmin)](https://qiita.com/yusabana/items/78e8d1ed64ead5fe9e29)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-06-22 23:55 UTC, T-Tsujii requested changes

2021-06-22 23:55 UTC, T-Tsujii commented on app/admin/movies.rb
> +  permit_params do
`permit_params` は重要なので一番上に書いた方がよいですね。

あと，中途半端にコメントを残してもメリットがないので，全部消すか，元の元を一番下に残すかのいずれかにした方がよいですよ。

2021-06-23 13:42 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-28 01:15 UTC, akihiro-cmd commented
LGTMです！

2021-06-28 01:15 UTC, akihiro-cmd approved these changes

2021-06-28 13:09 UTC, merged